#pragma once
#define CONFIG_FILENAME "PocketTrivia.cfg"

#define EXCEPTION_READING_QUESTION_FILE 101
#define EXCEPTION_READING_ANSWER_FILE 102

#define ERROR_ALLEGRO_INIT 103
#define ERROR_ALLEGRO_SOUND_INIT 104
#define ERROR_ALLEGRO_KEYBOARD_INIT 105
#define ERROR_ALLEGRO_GFX_CHANGE 106